### ISSUE TITLE
flag issue

### ISSUE THREAD

**Issue by u007** [markbates/grift#18]
hi,

ive encounter issue when i tried to run and pass in parameter with - numbers.
where by -1 is the limit of records to unlimited. it does works if we dont use any - hypen.
example:
```
grift mytask -1
```
and also grift does not support flags like --limit or -limit right?

thanks

**Comment by markbates** [comment]
Flags aren’t supported, no. Try quoting the number “-1”. Go is probably trying to interpret it as a flag, if the quoting doesn’t work, please re-open this issue. Thanks.

**Comment by u007** [comment]
on dev, "-1" does not work
i havent test on build
