### ISSUE TITLE
grift fails to find "grifts"-directory

### ISSUE THREAD

**Issue by maxmeyer** [markbates/grift#22]
# Error

Running

~~~
# version 0..4.0
grift
~~~

in directory, results in error message:

~~~
There is no directory named 'grifts'. Run 'grift init' or switch to the appropriate directory
~~~

~~~
$ pwd
# => ~/tmp/blub.2.2
~~~

# Expected result

The grift is found and run also in projects which are not in GOPATH.

# More information

I use `grift` in non-go-projects. With version `0.4.0` this is not possible anymore.

**Comment by rohanthewiz** [comment]
I have the same issue on Windows 10.
Git Bash
```
$ go version #=> go version go1.10.1 windows/amd64
$ grift -v #=> v1.0.2
$ grift init
$ ls -al
total 32
drwxr-xr-x 1 Rohan 1049089 0 Sep  5 16:34 ./
drwxr-xr-x 1 Rohan 1049089 0 Sep  5 16:34 ../
drwxr-xr-x 1 Rohan 1049089 0 Sep  5 16:34 grifts/
$ ls -R
.:
grifts/

./grifts:
example.go
$ grift list
There is no directory named 'grifts'. Run 'grift init' or switch to the appropriate directory
```

**Comment by u007** [comment]
it seems to happen when your directory is not within $GOPATH/src/

**Comment by u007** [comment]
with this, it should be allowed to run on non GOPATH

**Comment by u007** [comment]
@markbates any updates on this?
