### ISSUE TITLE
Grift not using vendor as a default path.

### ISSUE THREAD

**Issue by kumarsiva07** [markbates/grift#3]
I m using golang dep for dependancy management. 
`**grift routes**
/go/src/grift.build/8c375bea22/grifts/migrate.go:12:2: cannot find package "github.com/emirpasic/gods/sets/hashset" in any of:
    /usr/local/go/src/github.com/emirpasic/gods/sets/hashset (from $GOROOT)
    /go/src/github.com/emirpasic/gods/sets/hashset (from $GOPATH)
/go/src/grift.build/8c375bea22/grifts/migrate.go:13:2: cannot find package "github.com/jinzhu/gorm" in any of:
    /usr/local/go/src/github.com/jinzhu/gorm (from $GOROOT)
    /go/src/github.com/jinzhu/gorm (from $GOPATH)`

But Grift still searching only in GOPATH & GOROOT

**Comment by dilumn** [comment]
I'm having this same issue. Any solution for this??
