### ISSUE TITLE
grifter/main.go:4:8: cannot find package

### ISSUE THREAD

**Issue by Biboswan** [markbates/grift#33]
`
grifter/main.go:4:8: cannot find package "fixme_backend/grifts" in any of:
        /usr/local/Cellar/go/1.11.5/libexec/src/fixme_backend/grifts (from $GOROOT)
        /Users/biboswanroy/Go/src/fixme_backend/grifts (from $GOPATH)
`

Current directory:  /Users/biboswanroy/Go/src/github.com/ossn/fixme_backend/
GOPATH=/Users/biboswanroy/Go
I have grift command working.

I see same issue before as well but it didn't help me.

**Comment by justinkiang** [comment]
I'm seeing this problem as well :(

**Comment by mdouchement** [comment]
I'm running the same issue because my `GOPATH` contains 2 paths.
e.g. `/first/path/to/a/gopath:/second/path/to/a/gopath`

By specifying only one path, it works.
