### ISSUE TITLE
Using grift on windows can produce invalid import statements

### ISSUE THREAD

**Issue by LordRalex** [markbates/grift#8]
I have built a project using IntelliJ as my base on a Windows 10 machine, using the following version of Go
go version go1.8 windows/amd64

I have been trying to use the following command to run some grifts with buffalo, but it has not been successful.

```
C:\Users\Joshua\Projects\PufferPanel\PufferPanel\src\github.com\pufferpanel\pufferpanel>buffalo task db:seed
Buffalo version 0.8.2

package main:
grift_runner.go:4:22: unknown escape sequence
grift_runner.go:4:34: unknown escape sequence
grift_runner.go:4:46: unknown escape sequence
Usage:
  buffalo task [flags]

Aliases:
  task, t, tasks

Flags:
  -h, --help   help for task

Error: exit status 1
```

After digging into the file, I noticed that it was creating import paths using my local machine's path separator, which appeared to cause the issue. When I change the path to use the more known Golang version, I am able to use go run grift_runner.go without issue.

I narrowed down the actual offending call to be this one: https://github.com/markbates/grift/blob/master/cmd/grifter.go#L45

It uses the filepath joining method to generate the path, which works on Linux, but does not work well on Windows, or at least, on my own environment.

As per the spec, implementations can \ as an invalid character, and using the Golang.org version of 1.8 for Windows does not permit \ in the import paths. 
grift_runner.go:4:22: unknown escape sequence
https://golang.org/ref/spec#Import_declarations

The lexical rules say it's valid, but the windows binary of golang does not.

This being the offending line -> 
```
import _ "github.com\pufferpanel\pufferpanel\grifts"
```

Since grift wants to always override the file, I cannot use any of the provided methods to actually run it, as it will override any changes to the file, and even making it readonly will not let me run the tasks.

I cannot tell if this is just a "me" issue, but it's effectively been killing me trying to work with it, and seems odd that I'd be the first to really notice it.

**Comment by markbates** [comment]
Wow, I really wish all bug reports were this detailed! Thanks!

I fixed the issue. If you pull down the master of Grift and rebuild your Buffalo binary, it should all work fine for you. Hopefully. :)
